### ISSUE TITLE
Downloads useless(?) HTML files

### ISSUE THREAD

**Issue by alexanderadam** [miry/medup#22]
Also a complicated one and should therefore also only be done if there's nothing else to do. :wink:
Related to [issue 21](https://github.com/miry/medup/issues/21).

iFrames will usually result in html assets that don't contain the content but rather a bit HTML and much JS that will embedd an iFrame on it's own.

Maybe it would be better if there would be a better handler for this.

For example:

for some, very common things it would be good if there would be a dedicated handler. And for everything unknown it would probably be good to [make a screenshot (see issue 21)](https://github.com/miry/medup/issues/21).

Dedicated handlers could be:

* [x] gists ([example](https://building.buildkite.com/5-ways-weve-improved-flakey-test-debugging-4b3cfb9f27c8)) - because it's usually static text anyway and can be natively embedded into markdown (maybe a Shard like [octokit.cr](https://github.com/watzon/octokit.cr/blob/014e5da813b11a9e264c31ad49753c815f17b831/src/octokit/models/gists.cr) would help making this easier) #39 
* [x] Tweets ([example](https://copyconstruct.medium.com/testing-microservices-the-sane-way-9bb31d158c16) [example](https://medium.com/free-code-camp/vue-js-introduction-for-people-who-know-just-enough-jquery-to-get-by-eab5aa193d77) - `/assets/389f1de783e622ff4953bc8c0f01db80.html`) (there's [twitter-crystal](https://github.com/sferik/twitter-crystal) which might help) #44
* [x] Youtube ([example 1](https://medium.com/notes-and-tips-in-full-stack-development/modify-binary-files-with-vim-c35b40c499e) [example 2](https://medium.com/notes-and-tips-in-full-stack-development/medup-backups-articles-8bf90179b094)) - #42
* [x] General Embedy element - #45

**Comment by miry** [comment]
Covered gist in https://github.com/miry/medup/pull/39

**Comment by alexanderadam** [comment]
You. are. awesome.

**Comment by miry** [comment]
Replaced most of HTML files with inline links. 
Released [v0.4.0](https://github.com/miry/medup/releases/tag/v0.4.0).
